"""
config.py
---------
Application-wide constants: file paths, colours, and display defaults.
Edit this file to adapt to a different data release or organism.

Priority feature groups are configured separately via priority_groups.tsv
(generated by setup/s04_priority_groups.py).
"""

import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Organism metadata
# Used in GenBank output and UI labels.
# ---------------------------------------------------------------------------
ORGANISM_NAME  = "Caenorhabditis elegans"   # full name for GenBank /organism
ORGANISM_SHORT = "C. elegans"               # abbreviation for UI / descriptions

# ---------------------------------------------------------------------------
# Data file paths
# Defaults to ./data alongside this file. Override the root directory via the
# GFF_APP_DATA_DIR environment variable (useful on shinyapps.io or for testing
# against a different release).
# ---------------------------------------------------------------------------
DATA_DIR   = Path(os.environ.get(
    "GFF_APP_DATA_DIR",
    str(Path(__file__).parent / "data")
))
GFF_PATH              = DATA_DIR / "c_elegans.annotations.gff2genbank.gff3.gz"
FASTA_PATH            = DATA_DIR / "c_elegans.PRJNA13758.WS259.genomic.fa.gz"
DB_PATH               = DATA_DIR / "c_elegans.annotations.gff2genbank.gff3.gz.db"
# Priority groups TSV — stored in data/ alongside the other data files.
PRIORITY_GROUPS_PATH  = DATA_DIR / "worm_default.priority_groups.tsv"

# ---------------------------------------------------------------------------
# Default region loaded automatically on startup.
# Format: "chrom:start-end" (1-based, inclusive).
# Also used as the placeholder/default value in the coordinates input box.
# Set this to a region that is a good sanity-check for your organism/database.
# ---------------------------------------------------------------------------
DEFAULT_REGION = "III:10,901,491-10,910,085"

# Default gene name shown in the gene-name input box.
DEFAULT_GENE = "unc-119"

# ---------------------------------------------------------------------------
# Loading behaviour
# LOAD_FLANK  — bp loaded on each side of the target gene/region.
#               Should be large enough for comfortable panning.
# VIEW_FLANK  — initial Plotly x-axis window around the target (±).
#               Smaller than LOAD_FLANK so flanking sequence is available
#               by scrolling, but the gene is centred on first load.
# ---------------------------------------------------------------------------
LOAD_FLANK = 10_000
VIEW_FLANK = 1_000

# ---------------------------------------------------------------------------
# Feature types that are always excluded from the flat annotation toggle list.
# These are structural types rendered by the transcript track.
#
# Variation/priority feature types are NO LONGER listed here — they are
# excluded from the flat list at runtime based on what priority_groups.tsv
# actually claims.  This means unclaimed variation types always fall through
# to the flat list and are never hidden from the user.
# ---------------------------------------------------------------------------
ALWAYS_HANDLED = {
    # Gene-level containers
    "gene", "ncRNA_gene", "pseudogene", "transposable_element_gene",
    # Transcript containers — all types handled by the transcript track.
    # These are excluded from the extra_features loop in genbank.py to
    # prevent duplication (the transcript track already writes them).
    "mRNA",
    "ncRNA", "piRNA", "lincRNA", "pre_miRNA", "miRNA",
    "snoRNA", "snRNA", "rRNA", "tRNA", "pseudogenic_transcript",
    # Structural child features (rendered inside each transcript row)
    "exon", "CDS", "five_prime_UTR", "three_prime_UTR", "intron",
}

# Types that identify the 3' UTR (used for arrowhead direction logic in plot.py)
THREE_PRIME_UTR_TYPES = {"three_prime_UTR"}

# Types considered "variation" features — used by diagnose_variants.py.
VARIATION_TYPES = {
    "point_mutation", "deletion", "insertion",
    "substitution", "tandem_duplication",
    "complex_change_in_nucleotide_sequence",
    "complex_substitution",
    "sequence_alteration",
    "insertion_site",
    "transposable_element_insertion_site",
}

# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------
FEATURE_COLORS: dict[str, str] = {
    "CDS":                   "#1a8a4a",   # dark green
    "exon":                  "#2ecc71",   # light green  (non-coding transcripts)
    "intron":                "#aaaaaa",   # grey
    "five_prime_UTR":        "#f39c12",   # amber
    "three_prime_UTR":       "#e67e22",   # orange
    "ncRNA":                 "#9b59b6",
    "piRNA":                 "#8e44ad",
    "lincRNA":               "#1abc9c",
    "pseudogenic_transcript":"#bdc3c7",
    "pre_miRNA":             "#e91e63",
    "miRNA":                 "#e91e63",
    "snoRNA":                "#3498db",
    "snRNA":                 "#2980b9",
    "rRNA":                  "#c0392b",
    "tRNA":                  "#e74c3c",
}


# ---------------------------------------------------------------------------
# Interactive color palette
# 16 colors biased toward medium/light shades for readability in sequence
# viewers (ApE, Benchling, SnapGene) that render features on colored backgrounds.
# ---------------------------------------------------------------------------
PALETTE = [
    # Row 1: red → orange → yellow → green → teal
    "#E05C5C",  # medium red
    "#F0954A",  # medium orange
    "#F0B775",  # light peach
    "#F5C842",  # medium yellow
    "#D4E157",  # yellow-green
    "#7DCE82",  # light green
    "#1F9E58",  # medium green
    "#4BBFB0",  # medium teal
    "#80CBC4",  # light teal-green
    "#7EC8E3",  # light blue
    # Row 2: blue → purple → pink → neutrals
    "#2176AE",  # medium blue
    "#7B8FD4",  # medium periwinkle
    "#A87CC7",  # medium purple
    "#C9A8E0",  # light purple
    "#E86CA0",  # medium pink
    "#F4A7C3",  # light pink
    "#9E9E9E",  # medium gray
    "#BDBDBD",  # light gray
    "#D9D9D9",  # very light gray
    "#C4A882",  # light warm brown
]

# Default color map for all feature and variant group types.
# This is the starting point for per-session color overrides.
# Any type not listed here falls back to "#9E9E9E" (medium gray).
DEFAULT_COLORS: dict[str, str] = dict(FEATURE_COLORS)
