"""
s04_priority_groups.py
----------------------
Interactive setup module for defining PRIORITY_GROUPS — named groups of
(source, featuretype) pairs that get their own dedicated panel in the app UI.

Features that are not assigned to any group fall through to the standard
flat annotation list.  Features that are explicitly excluded are hidden
from the app entirely.

Position in workflow:
    prepare_gff.py  →  build_db.py  →  [this script]  →  app launch

Usage (standalone):
    python setup/s04_priority_groups.py --db path/to/annotations.db
    python setup/s04_priority_groups.py --db path/to/annotations.db --out priority_groups.tsv

Usage (via orchestrator):
    from setup.s04_priority_groups import run
    run(session)   # session dict carries db_path, data_dir, etc.

TSV format written:
    # comment lines are ignored
    group_name<TAB>source<TAB>featuretype<TAB>status
    # status is either 'include' (default) or 'exclude'
    # Use * to match any value in source or featuretype.
    # Groups are applied in order; first match wins.
"""

import argparse
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Feature types the app always handles internally — never show in priority
# group setup.  Kept in sync with config.ALWAYS_HANDLED.
# ---------------------------------------------------------------------------
_ALWAYS_HANDLED = {
    "gene", "ncRNA_gene", "pseudogene", "transposable_element_gene",
    "mRNA", "transcript",
    "exon", "CDS", "five_prime_UTR", "three_prime_UTR", "intron",
}


# ---------------------------------------------------------------------------
# TSV I/O
# ---------------------------------------------------------------------------

def load_tsv(tsv_path: Path) -> tuple[list[tuple[str, str, str, str]], list[str]]:
    """
    Load an existing priority_groups.tsv.

    Returns:
        rows    — list of (group_name, source, featuretype, status)
        comments — leading comment/header lines to preserve on re-save
    """
    rows: list[tuple[str, str, str, str]] = []
    comments: list[str] = []
    header_done = False

    with open(tsv_path) as fh:
        for line in fh:
            stripped = line.rstrip("\n")
            if stripped.startswith("#") or stripped.startswith("group_name"):
                if not header_done:
                    comments.append(stripped)
                continue
            header_done = True
            parts = stripped.split("\t")
            if len(parts) < 3:
                continue
            group  = parts[0].strip()
            source = parts[1].strip()
            feat   = parts[2].strip()
            status = parts[3].strip() if len(parts) >= 4 else "include"
            if group:
                rows.append((group, source, feat, status))

    return rows, comments


def save_tsv(tsv_path: Path, rows: list[tuple[str, str, str, str]]) -> None:
    """Write priority_groups.tsv from a list of (group, source, feat, status)."""
    with open(tsv_path, "w") as fh:
        fh.write("# priority_groups.tsv\n")
        fh.write("# Generated by s04_priority_groups.py\n")
        fh.write("# group_name  source  featuretype  status\n")
        fh.write("# status: 'include' (shown in priority panel) or 'exclude' (hidden)\n")
        fh.write("# Use * to match any value in source or featuretype.\n")
        fh.write("# Groups are applied in order; first match wins.\n")
        fh.write("group_name\tsource\tfeaturetype\tstatus\n")
        for group, source, feat, status in rows:
            fh.write(f"{group}\t{source}\t{feat}\t{status}\n")
    print(f"\nSaved: {tsv_path}")


# ---------------------------------------------------------------------------
# DB scanning
# ---------------------------------------------------------------------------

def scan_db(db_path: Path) -> list[tuple[str, str, int]]:
    """
    Return all (source, featuretype, count) tuples from the gffutils DB,
    excluding internally-handled feature types, sorted by count descending.
    """
    try:
        import gffutils
    except ImportError:
        print("ERROR: gffutils is not installed. Run: pip install gffutils")
        sys.exit(1)

    db = gffutils.FeatureDB(str(db_path))

    # gffutils exposes a direct connection we can query
    cur = db.conn.execute(
        "SELECT source, featuretype, COUNT(*) as n "
        "FROM features "
        "GROUP BY source, featuretype "
        "ORDER BY n DESC"
    )
    pairs = [
        (row[0], row[1], row[2])
        for row in cur.fetchall()
        if row[1] not in _ALWAYS_HANDLED
        and row[0] not in ("", ".")
        and row[1] not in ("", ".")
    ]
    return pairs


# ---------------------------------------------------------------------------
# Matching helpers
# ---------------------------------------------------------------------------

def matches(source: str, feat: str, pat_source: str, pat_feat: str) -> bool:
    """Return True if (source, feat) matches the (possibly wildcarded) pattern."""
    s_ok = (pat_source == "*") or (pat_source == source)
    f_ok = (pat_feat   == "*") or (pat_feat   == feat)
    return s_ok and f_ok


def classify_pair(
    source: str,
    feat: str,
    rows: list[tuple[str, str, str, str]],
) -> tuple[str | None, str]:
    """
    Return (group_name, status) for the first row that matches (source, feat).
    Returns (None, 'unassigned') if no row matches.
    """
    for group, pat_s, pat_f, status in rows:
        if matches(source, feat, pat_s, pat_f):
            return group, status
    return None, "unassigned"


# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------

def _label_width(pairs: list[tuple[str, str, int]]) -> tuple[int, int]:
    sw = max((len(s) for s, _, _ in pairs), default=10)
    fw = max((len(f) for _, f, _ in pairs), default=10)
    return sw, fw


def display_pairs(
    pairs: list[tuple[str, str, int]],
    rows: list[tuple[str, str, str, str]],
    show_index: bool = True,
) -> None:
    """Print the full pair table with current assignment status."""
    sw, fw = _label_width(pairs)
    header = (
        f"  {'#':>4}  {'SOURCE':<{sw}}  {'FEATURETYPE':<{fw}}  {'COUNT':>8}  ASSIGNED TO"
        if show_index else
        f"  {'SOURCE':<{sw}}  {'FEATURETYPE':<{fw}}  {'COUNT':>8}  ASSIGNED TO"
    )
    print()
    print(header)
    print("  " + "-" * (len(header) - 2))

    for i, (source, feat, count) in enumerate(pairs, 1):
        group, status = classify_pair(source, feat, rows)
        if status == "exclude":
            assignment = "[EXCLUDED]"
        elif group:
            assignment = group
        else:
            assignment = "-"

        if show_index:
            print(f"  {i:>4}  {source:<{sw}}  {feat:<{fw}}  {count:>8,}  {assignment}")
        else:
            print(f"  {source:<{sw}}  {feat:<{fw}}  {count:>8,}  {assignment}")
    print()


def display_groups(rows: list[tuple[str, str, str, str]]) -> None:
    """Print current group definitions."""
    if not rows:
        print("  (no groups defined)")
        return

    # Collect groups in order
    seen_groups: list[str] = []
    group_rows: dict[str, list[tuple[str, str, str]]] = {}
    excludes: list[tuple[str, str]] = []

    for group, source, feat, status in rows:
        if status == "exclude":
            excludes.append((source, feat))
        else:
            if group not in seen_groups:
                seen_groups.append(group)
                group_rows[group] = []
            group_rows[group].append((source, feat, status))

    for i, g in enumerate(seen_groups, 1):
        print(f"  {i}. {g}")
        for source, feat, _ in group_rows[g]:
            print(f"       source={source}  featuretype={feat}")

    if excludes:
        print(f"  [EXCLUDED]")
        for source, feat in excludes:
            print(f"       source={source}  featuretype={feat}")
    print()


# ---------------------------------------------------------------------------
# Prompting helpers
# ---------------------------------------------------------------------------

def prompt(msg: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{msg}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    return val if val else default


def prompt_indices(msg: str, max_n: int) -> list[int]:
    """
    Ask user to enter a list of numbers (1-based), ranges (3-7), or 'all'.
    Returns 0-based indices.
    """
    while True:
        raw = prompt(msg)
        if not raw:
            return []
        if raw.lower() == "all":
            return list(range(max_n))
        indices = []
        valid = True
        for part in raw.replace(",", " ").split():
            if "-" in part:
                try:
                    a, b = part.split("-", 1)
                    lo, hi = int(a), int(b)
                    if lo < 1 or hi > max_n or lo > hi:
                        raise ValueError
                    indices.extend(range(lo - 1, hi))
                except ValueError:
                    print(f"  Invalid range: '{part}'. Use e.g. 3-7.")
                    valid = False
                    break
            else:
                try:
                    n = int(part)
                    if n < 1 or n > max_n:
                        raise ValueError
                    indices.append(n - 1)
                except ValueError:
                    print(f"  Invalid number: '{part}'. Must be 1–{max_n}.")
                    valid = False
                    break
        if valid:
            # deduplicate preserving order
            seen: set[int] = set()
            return [x for x in indices if not (x in seen or seen.add(x))]


def prompt_group_name(
    rows: list[tuple[str, str, str, str]],
    action: str = "assign to",
) -> str | None:
    """
    Ask the user to pick an existing group or create a new one.
    Returns the group name, or None to cancel.
    """
    existing = []
    seen: set[str] = set()
    for group, _, _, status in rows:
        if status == "include" and group not in seen:
            existing.append(group)
            seen.add(group)

    print(f"\n  Existing groups:")
    for i, g in enumerate(existing, 1):
        print(f"    {i}. {g}")
    print(f"    n. Create new group")
    print(f"    x. Cancel")

    choice = prompt("  Choice").lower()
    if choice == "x" or not choice:
        return None
    if choice == "n":
        name = prompt("  New group name").strip()
        return name if name else None
    try:
        idx = int(choice) - 1
        if 0 <= idx < len(existing):
            return existing[idx]
    except ValueError:
        pass
    print("  Invalid choice.")
    return None


# ---------------------------------------------------------------------------
# Main editing loop
# ---------------------------------------------------------------------------

def edit_loop(
    pairs: list[tuple[str, str, int]],
    rows: list[tuple[str, str, str, str]],
) -> list[tuple[str, str, str, str]]:
    """
    Interactive editing loop.  Returns updated rows.
    """
    while True:
        print("\n" + "=" * 60)
        print("PRIORITY GROUPS — MAIN MENU")
        print("=" * 60)
        print("  1. Show all (source, featuretype) pairs with assignments")
        print("  2. Show current group definitions")
        print("  3. Assign pairs to a group")
        print("  4. Exclude pairs from the app entirely")
        print("  5. Unassign pairs (move back to flat list)")
        print("  6. Rename a group")
        print("  7. Reorder groups")
        print("  8. Delete a group (unassigns all its pairs)")
        print("  s. Save and exit")
        print("  q. Quit without saving")

        choice = prompt("\nChoice").lower()

        if choice == "1":
            display_pairs(pairs, rows)

        elif choice == "2":
            display_groups(rows)

        elif choice == "3":
            display_pairs(pairs, rows)
            indices = prompt_indices(
                "Enter pair numbers to assign (e.g. 1 3 5-8, or 'all')",
                len(pairs),
            )
            if not indices:
                continue
            group = prompt_group_name(rows, "assign to")
            if not group:
                continue
            # Remove existing assignments for selected pairs, then add new ones
            selected = {(pairs[i][0], pairs[i][1]) for i in indices}
            rows = [
                r for r in rows
                if not any(matches(r[1], r[2], s, f) for s, f in selected)
                # keep rows whose pattern doesn't exactly match any selected pair
                # (exact match only — don't remove wildcard rows covering other pairs)
            ]
            # For wildcard safety: remove rows only if pattern matches exactly
            rows = _remove_exact(rows, selected)
            # Find the insertion point: after the last row of this group if it exists
            rows = _insert_for_group(rows, group, [
                (group, pairs[i][0], pairs[i][1], "include") for i in indices
            ])
            print(f"  Assigned {len(indices)} pair(s) to '{group}'.")

        elif choice == "4":
            display_pairs(pairs, rows)
            indices = prompt_indices(
                "Enter pair numbers to exclude",
                len(pairs),
            )
            if not indices:
                continue
            selected = {(pairs[i][0], pairs[i][1]) for i in indices}
            rows = _remove_exact(rows, selected)
            for source, feat in selected:
                rows.append(("_excluded_", source, feat, "exclude"))
            print(f"  Excluded {len(indices)} pair(s).")

        elif choice == "5":
            display_pairs(pairs, rows)
            indices = prompt_indices(
                "Enter pair numbers to unassign",
                len(pairs),
            )
            if not indices:
                continue
            selected = {(pairs[i][0], pairs[i][1]) for i in indices}
            rows = _remove_exact(rows, selected)
            print(f"  Unassigned {len(indices)} pair(s).")

        elif choice == "6":
            display_groups(rows)
            groups = _group_order(rows)
            if not groups:
                print("  No groups to rename.")
                continue
            idx_s = prompt("  Group number to rename")
            try:
                idx = int(idx_s) - 1
                old_name = groups[idx]
            except (ValueError, IndexError):
                print("  Invalid choice.")
                continue
            new_name = prompt(f"  New name for '{old_name}'").strip()
            if not new_name:
                continue
            rows = [
                (new_name if g == old_name else g, s, f, st)
                for g, s, f, st in rows
            ]
            print(f"  Renamed '{old_name}' → '{new_name}'.")

        elif choice == "7":
            groups = _group_order(rows)
            if len(groups) < 2:
                print("  Need at least two groups to reorder.")
                continue
            print("\n  Current order:")
            for i, g in enumerate(groups, 1):
                print(f"    {i}. {g}")
            new_order_s = prompt(
                "  Enter new order as numbers (e.g. 3 1 2)"
            )
            try:
                new_order = [int(x) - 1 for x in new_order_s.split()]
                if sorted(new_order) != list(range(len(groups))):
                    raise ValueError
            except (ValueError, IndexError):
                print("  Invalid order — must list each group number exactly once.")
                continue
            ordered_groups = [groups[i] for i in new_order]
            # Rebuild rows in new group order, preserving exclude rows at end
            exclude_rows = [r for r in rows if r[3] == "exclude"]
            include_rows = [r for r in rows if r[3] != "exclude"]
            reordered: list[tuple[str, str, str, str]] = []
            for g in ordered_groups:
                reordered.extend(r for r in include_rows if r[0] == g)
            rows = reordered + exclude_rows
            print(f"  Reordered: {' → '.join(ordered_groups)}")

        elif choice == "8":
            display_groups(rows)
            groups = _group_order(rows)
            if not groups:
                print("  No groups to delete.")
                continue
            idx_s = prompt("  Group number to delete")
            try:
                idx = int(idx_s) - 1
                name = groups[idx]
            except (ValueError, IndexError):
                print("  Invalid choice.")
                continue
            confirm = prompt(f"  Delete '{name}' and unassign all its pairs? (y/n)", "n")
            if confirm.lower() != "y":
                continue
            rows = [r for r in rows if r[0] != name or r[3] == "exclude"]
            print(f"  Deleted group '{name}'.")

        elif choice == "s":
            return rows

        elif choice == "q":
            confirm = prompt("Quit without saving? (y/n)", "n")
            if confirm.lower() == "y":
                return None  # signal: don't save

        else:
            print("  Unrecognised option.")

    return rows


# ---------------------------------------------------------------------------
# Row manipulation helpers
# ---------------------------------------------------------------------------

def _remove_exact(
    rows: list[tuple[str, str, str, str]],
    selected: set[tuple[str, str]],
) -> list[tuple[str, str, str, str]]:
    """Remove rows whose (source, featuretype) exactly matches a selected pair."""
    return [r for r in rows if (r[1], r[2]) not in selected]


def _group_order(rows: list[tuple[str, str, str, str]]) -> list[str]:
    """Return group names in current order (include rows only, deduplicated)."""
    seen: set[str] = set()
    out = []
    for group, _, _, status in rows:
        if status == "include" and group not in seen:
            out.append(group)
            seen.add(group)
    return out


def _insert_for_group(
    rows: list[tuple[str, str, str, str]],
    group: str,
    new_rows: list[tuple[str, str, str, str]],
) -> list[tuple[str, str, str, str]]:
    """
    Insert new_rows after the last existing row for `group`.
    If the group doesn't exist yet, append at the end of include rows
    (before any exclude rows).
    """
    last_idx = -1
    for i, (g, _, _, st) in enumerate(rows):
        if g == group and st == "include":
            last_idx = i

    if last_idx >= 0:
        return rows[: last_idx + 1] + new_rows + rows[last_idx + 1 :]

    # New group — insert before exclude rows
    first_exclude = next(
        (i for i, r in enumerate(rows) if r[3] == "exclude"), len(rows)
    )
    return rows[:first_exclude] + new_rows + rows[first_exclude:]


# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------

def run(session: dict) -> dict:
    """
    Orchestrator entry point.

    Expected session keys:
        db_path   (Path)  — gffutils database
        data_dir  (Path)  — where to write priority_groups.tsv

    Updates session with:
        priority_groups_path  (Path)
    """
    from setup_log import write_step
    data_dir = Path(session["data_dir"])

    db_path = Path(session.get("db_path", ""))
    if not db_path.exists():
        print(f"\n  ERROR: Database not found at {db_path}")
        print("  Run s03 first, or pass --db to the standalone script.")
        write_step(data_dir, "s04_priority_groups", "failed",
                   message="Database not found — run s03 first.")
        return session

    out_path = data_dir / "priority_groups.tsv"
    _run_interactive(db_path, out_path)
    session["priority_groups_path"] = str(out_path)

    status = "ok" if out_path.exists() else "skipped"
    msg    = f"Written: {out_path}" if out_path.exists() else "Exited without saving."
    write_step(data_dir, "s04_priority_groups", status,
               message=msg, output=out_path if out_path.exists() else None)
    return session


def _run_interactive(db_path: Path, out_path: Path) -> None:
    print("\n" + "=" * 60)
    print("STEP 4: CONFIGURE PRIORITY GROUPS")
    print("=" * 60)
    print(f"Database : {db_path}")
    print(f"Output   : {out_path}")

    # Load existing TSV if present
    rows: list[tuple[str, str, str, str]] = []
    if out_path.exists():
        rows, _ = load_tsv(out_path)
        print(f"\nLoaded existing priority_groups.tsv ({len(rows)} row(s)).")
    else:
        print("\nNo existing priority_groups.tsv found — starting fresh.")

    # Scan DB
    print("\nScanning database for (source, featuretype) pairs...")
    pairs = scan_db(db_path)
    print(f"Found {len(pairs)} distinct pair(s) (structural features excluded).")

    if not pairs:
        print("Nothing to configure — all features are structural.")
        return

    # Edit loop
    updated = edit_loop(pairs, rows)

    if updated is None:
        print("Exited without saving.")
        return

    save_tsv(out_path, updated)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Configure priority feature groups for the GFF->GenBank app.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--db", required=True,
        help="Path to the gffutils database (.db) built by build_db.py / s03.",
    )
    parser.add_argument(
        "--out", default=None,
        help="Output TSV path (default: priority_groups.tsv alongside the DB).",
    )
    args = parser.parse_args()

    db_path  = Path(args.db)
    out_path = Path(args.out) if args.out else db_path.parent / "priority_groups.tsv"

    if not db_path.exists():
        print(f"ERROR: Database not found: {db_path}")
        sys.exit(1)

    _run_interactive(db_path, out_path)


if __name__ == "__main__":
    main()
